export const ENTITIES = {
  USERS: 'USERS',
  ORGANIZATIONS: 'ORGANIZATIONS',
  BUSINESS_UNITS: 'BUSINESS_UNITS',
  PROVIDERS: 'PROVIDERS',
  LEVELS: 'LEVELS'
};

export const OPERATIONS = {
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE'
};

export const NODE_TYPES = {
  ORGANIZATION: 'ORG',
  BUSINESS_UNIT: 'BU',
  PROVIDER: 'PR',
  PATIENT: 'PAT'
};
